site_name: Numerical Solutions to ODE's

nav:
  - Home: index.md
  - Reference: reference.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: change to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: change to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false  # Puedes ajustar esta opción según tus necesidades

plugins:
  - search

